# Generated by Django 2.2.4 on 2019-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190908_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
