# Generated by Django 2.2.4 on 2019-09-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
    ]
