# Generated by Django 2.2.4 on 2019-09-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_attendance_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='days',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
    ]
