# Generated by Django 2.2.4 on 2019-09-08 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190908_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
