# Generated by Django 2.2.4 on 2019-09-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190909_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
